name: example
description: A sample for to_string usage.
homepage: https://github.com/lvsecoto/to_string
version: 1.0.0
author: lvsecoto <lvsecoto@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  to_string:
    path: "../to_string"

dependency_overrides:
  to_string:
    path: "../to_string"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  to_string_generator:
    path: "../to_string_generator"
