name: to_string_generator
description: Builder and Generator for package to_string
homepage: https://github.com/lvsecoto/to_string
version: 1.3.0
author: lvsecoto <lvsecoto@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^1.3.0

  to_string: ^1.3.0

  # for testing unreleased version
  #to_string:
  #  path: ../to_string

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  build_runner: ^1.12.2
  source_gen_test: ^1.0.0
